# Generated by Django 4.0.4 on 2022-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('des', models.CharField(max_length=45)),
                ('dept', models.CharField(max_length=45)),
            ],
        ),
    ]
